Add Link properties for archive entry metadata
readium/r2-shared-swift pull request #144
Opened 2021-06-03 09:49 UTC by mickael-menu

### Added

* `Link` objects from archive-based publication assets (e.g. an EPUB/ZIP) have additional properties for entry metadata.
    ```json
    "properties" {
        "archive": {
            "entryLength": 8273,
            "isEntryCompressed": true
        }
    }
    ```

2021-06-03 13:20 UTC, aferditamuriqi requested changes

2021-06-03 13:20 UTC, aferditamuriqi commented on r2-shared-swift/Fetcher/ArchiveFetcher.swift
> +            originalLink.addingProperties(entry.linkProperties)
@mickael-menu apparently entry could be nil here 

>  Value of optional type 'ArchiveEntry?' must be unwrapped to refer to member 'linkProperties' of wrapped base type 'ArchiveEntry'

this should do it:

```
            if let entry = entry {
                return originalLink.addingProperties(entry.linkProperties)
            }
            return originalLink
```

2021-06-03 13:40 UTC, mickael-menu commented on r2-shared-swift/Fetcher/ArchiveFetcher.swift
> +            originalLink.addingProperties(entry.linkProperties)
That's weird... I don't get this warning and `entry` is not optional in the type:

https://github.com/readium/r2-shared-swift/blob/35ed1ac117385a225e80ac9fba9ab63a0b34c9fa/r2-shared-swift/Fetcher/ArchiveFetcher.swift#L55

2021-06-04 00:23 UTC, aferditamuriqi commented on r2-shared-swift/Fetcher/ArchiveFetcher.swift
> +            originalLink.addingProperties(entry.linkProperties)
it sure is weird, but once i wrapped it as mentioned, it worked. i didn't check out the entire testapp etc. with this. but strange i would get the optional warning and you don't .

2021-06-04 00:24 UTC, aferditamuriqi commented on r2-shared-swift/Publication/Extensions/Archive/Properties+Archive.swift
> +    public var archive: Archive? {
@mickael-menu probably because here it turns into an optional.

2021-06-04 00:29 UTC, aferditamuriqi approved these changes

2021-06-04 00:29 UTC, aferditamuriqi commented on r2-shared-swift/Fetcher/ArchiveFetcher.swift
> +            originalLink.addingProperties(entry.linkProperties)
i'll resolve this comment, and since i confirmed this works, i 'll make sure to test it out again in the test app. but you were not going to merge it until next week anyway :)

2021-06-11 06:53 UTC, merged